# backend/schemas/chat.py
from pydantic import BaseModel, Field, field_validator
from typing import Literal

class ChatRequest(BaseModel):
    """
    Request schema representing the query submitted by the client.
    """
    query: str = Field(
        ...,
        description="The user query or question to be answered by the assistant.",
        min_length=1,
    )
    conversation_id: str | None = Field(
        default=None,
        description="Optional conversation identifier to track chat history."
    )
    session_id: str | None = Field(
        default=None,
        description="Optional session identifier to track user sessions."
    )

    @field_validator("query", mode="before")
    @classmethod
    def validate_and_strip_query(cls, v: str) -> str:
        if not isinstance(v, str):
            raise TypeError("query must be a string.")

        v = v.strip()

        if not v:
            raise ValueError(
                "Query cannot be empty or only whitespace."
            )

        return v


class SourceResponse(BaseModel):
    """
    Response schema representing metadata of a retrieved source chunk.
    """
    document: str = Field(
        ...,
        description="The name or identifier of the source document."
    )
    page: int = Field(
        ...,
        ge=1,
        description="The page number where the source content is located."
    )
    section: str | None = Field(
        default=None,
        description="The section title or header within the document."
    )
    section_path: str | None = Field(
        default=None,
        description="The hierarchical section path within the document, e.g. 'Chapter 1 > Section 2'."
    )
    score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Relevance or retrieval confidence score, normalized between 0.0 and 1.0."
    )
    content_type: str | None = Field(
        default=None,
        description="The type of the source content, e.g. text or table."
    )
    chunk_id: str | None = Field(
        default=None,
        description="The unique identifier of the source chunk."
    )


class EvaluationResponse(BaseModel):
    """
    Response schema representing detailed evaluation scores and risk assessments.
    """
    passed: bool = Field(
        ...,
        description="True if the answer passed safety and quality thresholds."
    )
    overall_score: float | None = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="The overall consolidated evaluation score between 0.0 and 1.0."
    )
    grounding_score: float | None = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="Groundedness score indicating how well the answer is supported by the context."
    )
    coverage_score: float | None = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="Coverage score indicating how well the query matches the answer components."
    )
    citation_score: float | None = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="Score indicating accuracy and correctness of citations against the source metadata."
    )
    numerical_score: float | None = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="Score indicating accuracy of numbers, currencies, and dates compared to the context."
    )
    table_score: float | None = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="Score indicating tabular structure mapping correctness and row/column alignment."
    )
    hallucination_score: float | None = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="Factual accuracy score indicating absence of invented metrics or entities."
    )
    hallucination_risk: Literal["Low", "Medium", "High"] = Field(
        ...,
        description="Factual hallucination risk level based on mismatched entities."
    )
    confidence: float | None = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="Confidence score of the evaluation engine, between 0.0 and 1.0."
    )
    explanation: str = Field(
        ...,
        description="A human-readable summary explanation detailing the evaluation results."
    )
    warnings: list[str] = Field(
        default_factory=list,
        description="Detailed validation warnings or errors generated by the evaluation engine."
    )


class ChatResponse(BaseModel):
    """
    Consolidated RAG response schema containing the answer, sources, and evaluation data.
    """
    answer: str = Field(
        ...,
        description="The generated answer from the assistant."
    )
    evaluation: EvaluationResponse = Field(
        ...,
        description="The nested response quality and safety evaluation scores."
    )
    sources: list[SourceResponse] = Field(
        ...,
        description="The list of retrieved sources used to generate the answer."
    )