# backend/agents/state.py

"""
This module defines the shared state schema for the Enterprise Knowledge Assistant
LangGraph agent pipeline. The state is used to pass context and intermediate results
between different graph nodes.
"""

from typing import NotRequired, TypedDict
from langchain_core.messages import BaseMessage
from backend.retrieval.retriever import RetrievalResult
from backend.llm.evaluator import EvaluationResult
from backend.agents.web_search import WebSearchResult
from typing import Literal


class EnterpriseState(TypedDict):
    """
    Represents the state of the Enterprise Knowledge Assistant workflow.

    Only the 'query' field is required to initialize the state. All other
    fields are optional and populated incrementally by graph nodes during execution.
    """

    query: str
    """The initial user query or question."""

    route: NotRequired[Literal["documents", "web", "hybrid"]]
    """The routing decision. Possible values: 'documents', 'web', 'hybrid'."""

    retrieval_results: NotRequired[list[RetrievalResult]]
    """The list of document chunks retrieved from the local vector database."""

    web_results: NotRequired[list[WebSearchResult]]
    """The list of raw content snippets retrieved from web search search results."""

    context: NotRequired[str]
    """The consolidated context constructed from retrieval or web search results."""

    answer: NotRequired[str]
    """The answer generated by the language model."""

    evaluation: NotRequired[EvaluationResult | None]
    """The outcome of evaluating the generated answer's safety, grounding, and coverage."""

    messages: NotRequired[list[BaseMessage]]
    """The history of conversation messages exchanged in the current agent loop."""
    
    sources: NotRequired[list[dict]]
    """The list of sources used to generate the answer, including metadata and provenance information."""